made  changes 1 #2

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -19,11 +19,11 @@ jobs:
         id: version
         run: |
         if [[ -f $GITHUB_WORKSPACE/version.txt ]]; the
-        echo "version = $(cat $GITHUB_WORKSPACE/version.txt)" >> $GITHUB_OUTPUT
+          echo "version = $(cat $GITHUB_WORKSPACE/version.txt)" >> $GITHUB_OUTPUT
         else
-        echo "version.txt file not found in the repository."
-      exit 1
-    fi
+          echo "version.txt file not found in the repository."
+        exit 1
+        fi
 
       - name: Assign version as a label
         run: |
